CREATE DATABASE IF NOT EXISTS PRIM_DATABASE
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

CREATE TABLE IF NOT EXISTS USUARIO(
	EMAIL_USER varchar(50) NOT NULL,
	NOME_USER varchar(20) NOT NULL,
	SENHA_USER varchar(30) NOT NULL,
	CONSTRAINT PK_USUARIO PRIMARY KEY (EMAIL_USER) 
)DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS CATEGORIA_EVENTO(
	ID_CATEGORIA_EVENTO int NOT NULL,
	NOME_CATEGORIA_EVENTO varchar(30) NOT NULL,
	CONSTRAINT PK_CATEGORIA_EVENTO PRIMARY KEY (ID_CATEGORIA_EVENTO) 
)DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS CATEGORIA_SERVICO(
	ID_CATEGORIA_SERVICO int NOT NULL,
	NOME_CATEGORIA_SERVICO varchar(30) NOT NULL,
	CONSTRAINT PK_CATEGORIA_SERVICO PRIMARY KEY (ID_CATEGORIA_SERVICO) 
)DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS EVENTO (
	ID_EVENTO int NOT NULL AUTO_INCREMENT,
	TITULO_EVENTO varchar(30) NOT NULL,
	DESCRICAO_EVENTO varchar(315),
	LOCALIZACAO_EVENTO char(9) NOT NULL,
	TELEFONE_EVENTO varchar(16) NOT NULL,
	DATA_EVENTO date NOT NULL,
	HORA_EVENTO time(0) NOT NULL,
	PRECO_EVENTO decimal(7,2) NOT NULL,
	TAXA_EVENTO decimal(5,2) NOT NULL,
	PUBLICO_EVENTO smallint NOT NULL,
	ING_VENDIDOS_EVENTO smallint NOT NULL,
	EMAIL_USER varchar(50) NOT NULL,
	ID_CATEGORIA_EVENTO int NOT NULL,
	CONSTRAINT PK_EVENTO PRIMARY KEY (ID_EVENTO),
	CONSTRAINT FK_EVENTO_USUARIO FOREIGN KEY (EMAIL_USER) REFERENCES USUARIO (EMAIL_USER),
	CONSTRAINT FK_EVENTO_CATEGORIA_EVENTO FOREIGN KEY (ID_CATEGORIA_EVENTO) REFERENCES CATEGORIA_EVENTO (ID_CATEGORIA_EVENTO)
)DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS SERVICO(
	ID_SERVICO int NOT NULL AUTO_INCREMENT,
	TITULO_SERVICO varchar(30) NOT NULL,
	DESCRICAO_SERVICO varchar(315),
	LOCALIZACAO_SERVICO char(9) NOT NULL,
	TELEFONE_SERVICO varchar(16) NOT NULL,
	PRECO_SERVICO decimal(7,2) NOT NULL,
	TAXA_SERVICO decimal(5,2) NOT NULL,
	EMAIL_USER varchar(50) NOT NULL,
	ID_CATEGORIA_SERVICO int NOT NULL,
	CONSTRAINT PK_SERVICO PRIMARY KEY (ID_SERVICO),
	CONSTRAINT FK_SERVICO_USUARIO FOREIGN KEY (EMAIL_USER) REFERENCES USUARIO (EMAIL_USER),
	CONSTRAINT FK_SERVICO_CATEGORIA_SERVICO FOREIGN KEY (ID_CATEGORIA_SERVICO) REFERENCES CATEGORIA_SERVICO (ID_CATEGORIA_SERVICO)
)DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS INGRESSO(
	ID_INGRESSO int NOT NULL AUTO_INCREMENT,	
	ID_EVENTO int NOT NULL,
	TITULO_INGRESSO varchar(30) NOT NULL,
	QUANTIDADE_INGRESSO smallint NOT NULL,
	EMAIL_USER varchar(50) NOT NULL,
	CONSTRAINT PK_INGRESSO PRIMARY KEY (ID_INGRESSO,ID_EVENTO), 
	CONSTRAINT FK_INGRESSO_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO (ID_EVENTO),
	CONSTRAINT FK_INGRESSO_USUARIO FOREIGN KEY (EMAIL_USER) REFERENCES USUARIO (EMAIL_USER)
)DEFAULT CHARSET=UTF8;
